site_name: 上田研 自律移動チーム
site_url: https://CIT-Autonomous-Robot-Lab.github.io/
site_author: CIT-Autonomous-Robot-Lab

repo_name: CIT-Autonomous-Robot-Lab/cit-autonomous-robot-lab
repo_url: https://github.com/CIT-Autonomous-Robot-Lab/cit_autonomous_robot_lab
repo: fontawesome/brands/github

copyright: Copyright &copy; 2024 CIT-Autonomous-Robot-Lab

theme:
    name: material
    language: ja
    logo: ./img/ueda_lab_symbol.png
    favicon: ./img/ueda_lab_symbol.png
    # 使用可能色は定義された21色
    #    red, pink, purple, deep purple, indigo, blue, light blue, cyan,
    #    teal,  green, light green, lime, yellow, amber, orange,
    #    deep orange,   brown, grey, blue grey, white
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    features:
        - navigation.tabs
        - navigation.top
        - navigation.expand
        - content.code.annotate
        - content.code.copy
        - content.code.select
        - content.code.annotate
    palette:
        - scheme: default
          primary: pink
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: ダークモードに切り替えます。

        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: ライトモードに切り替えます。
    icon:
      repo: fontawesome/brands/github

plugins:
    - search:
    - git-revision-date-localized:
        fallback_to_build_date: true
    - link-embeds:

extra:
    logo:
        # 利用可能なアイコンは以下を参照
        # https://material.io/resources/icons/?icon=description&style=baseline
        icon: 'developer_board'
    # ウェブアプリマニフェストを有効化
    manifest: 'manifest.webmanifest'
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/CIT-Autonomous-Robot-Lab

extra_css:
    - css/custom.css

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.superfences
    - footnotes
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details

nav:
    - Home:
        - 上田研究室　自律移動チーム: index.md
        - Tech Blog: tech_blog/tech_blog.md
    - Research: research/research.md
    - Achievement: achievement/achievement.md
    - Development: development/development.md
    - Tech Movie: tech_movie/tech_movie.md
    - Member: member/member.md
    - Contact: contact/contact.md
